### PR TITLE
Eliminate matcher code duplication

### PR DESCRIPTION
**Pull request by coreyhaines**
Single-value matchers are incredibly similar in implementation. I've done a bit of refactoring to pull out the actual differences. This will allow easier creation of new single-value matchers.
There's similar logic with multiple-value matchers that could be extracted, I'm sure. This is a good first step, though.

### CODE REVIEW

**Comment by coreyhaines** [comment]
Looking at the code, #success and #mismatch are used by the other matchers, so I can see keeping them.

What do you think about changing ::Match to ::Matcher, as it really represents what you are saying when you include it: "This thing I am creating is a matcher"

**Comment by zaphod42** [comment]
I think that sounds reasonable. We can always split it up later if need be.

**Comment by coreyhaines** [comment]
Definitely. As it grows a bit, we can start to see if there is an
abstraction around creating the match results. I'll make the name change
and add this to the pull request.

On Sun, Jul 1, 2012 at 12:57 PM, Andrew Parker <
reply@reply.github.com

**Comment by coreyhaines** [comment]
Made the name change. YAY sed!

**Pull request merged**
